"""added relationships

Revision ID: 053d360df6f8
Revises: 
Create Date: 2021-10-06 14:11:43.214329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053d360df6f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
