"""Added collection

Revision ID: 274a1fb964dc
Revises: 053d360df6f8
Create Date: 2021-10-06 16:04:14.278381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274a1fb964dc'
down_revision = '053d360df6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
