version: '3.7'
services:
    postgres:
        image: postgres:10.5
        restart: always
        environment: 
          - POSTGRES_DBNAME=pdm
          - POSTGRES_USER=pdm
          - POSTGRES_PASSWORD=pdm
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5332:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./create_articles_table.sql:/docker-entrypoint-initdb.d/create_tables.sql